services:

  frontend:
    #build: ./frontend
    image: ghcr.io/beny2000/receipt-scanner/frontend:latest
    ports:
     - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - REACT_APP_ENV=development
      - NODE_ENV=development

  backend:
    #build: ./backend
    image: ghcr.io/beny2000/receipt-scanner/backend:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app/app
      - ./system_prompt.txt:/app/system_prompt.txt
      - ./user_prompt.txt:/app/user_prompt.txt
    env_file:
      - .env
    environment:
      IS_TEST: "false"
      LOG_LEVEL: DEBUG
      MODEL_NAME: "gpt-4o-mini" # Must use a vision-enabled model
      ALLOWED_ORIGINS: "*"
      SYSTEM_PROMPT_FILE: /app/system_prompt.txt
      USER_PROMPT_FILE: /app/user_prompt.txt
      