services:
  frontend:
    image: node:18
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/receipt-scanner:/app
    command: sh -c "npm install && npm run start"
    #command: sh -c "npm install -g serve && serve -s build"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENV=development
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env
    environment:
      IS_TEST: false
      LOG_LEVEL: DEBUG
      MODEL_NAME: "gpt-4o-mini" # You must use a vision-enabled model
      ALLOWED_ORIGINS: "*"
      