name: Build and Deploy Backend and Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'

permissions:
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend Docker Image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${{ github.repository }}/backend:$GIT_COMMIT \
            -t ghcr.io/${{ github.repository }}/backend:latest \
            ./backend --push

      - name: Build and Push Frontend Docker Image
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${{ github.repository }}/frontend:$GIT_COMMIT \
            -t ghcr.io/${{ github.repository }}/frontend:latest \
            ./frontend --push